In [3]:
#Завантаження бібліотеки
import numpy as np

In [39]:
#Створіть одновимірний масив (вектор) із арифметичною прогресією, де кожне наступне число менше попереднього на 4,
#починаючи з 50, та виведіть його значення.
arr = np.arange(50, -1, -4)
print(arr)

[50 46 42 38 34 30 26 22 18 14 10  6  2]


In [40]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями суми добутків кожного числа на його попереднє,
#починаючи з 1, та виведіть його значення.
matrix = np.arange(1, 10).reshape(3, 3) * (np.arange(1, 10).reshape(3, 3) - 1)
print(matrix)


[[ 0  2  6]
 [12 20 30]
 [42 56 72]]


In [41]:
#Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні від -5 до 5 та знайдіть
#мінімальний елемент.
matrix = np.random.randint(-5,6,size=(3,3))
min_n = np.min(matrix)
print(matrix)
print("Мінімальний елемент:", min_n)


[[-1 -2 -2]
 [-2  1  0]
 [ 2  0  1]]
Мінімальний елемент: -2


In [42]:
#Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть
#добуток елементів, що менше 0.2.
random_matrix = np.random.random((3, 3))
result = np.prod(random_matrix[random_matrix < 0.2])
print(random_matrix)
print(f"Добуток елементів менше 0.2: {result}")

[[0.21311478 0.79747723 0.20884071]
 [0.12473394 0.9289779  0.3886479 ]
 [0.02259878 0.6139548  0.9849585 ]]
Добуток елементів менше 0.2: 0.00281883455299757


In [43]:
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від 0 до 1
#та виконайте на них поелементні операції додавання, віднімання та множення.
array_a = np.random.rand(4)
array_b = np.random.rand(4)
plus = array_a + array_b
minus = array_a - array_b
dobutok = array_a * array_b
print("Array A:", array_a)
print("Array B:", array_b)
print("Сума:", plus)
print("Різниця:", minus)
print("Добуток:", dobutok)

Array A: [0.76871442 0.08258804 0.3319113  0.65519476]
Array B: [0.1643778  0.04431446 0.78180299 0.64889813]
Сума: [0.93309223 0.1269025  1.11371428 1.30409289]
Різниця: [ 0.60433662  0.03827359 -0.44989169  0.00629664]
Добуток: [0.12635959 0.00365984 0.25948924 0.42515466]


In [44]:
#Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 5 до 10 та знайдіть їх добуток.
matrix_a = np.random.randint(5, 11, size=(3, 3))
matrix_b = np.random.randint(5, 11, size=(3, 3))
array = np.dot(matrix_a, matrix_b)
print("Матриця A:\n", matrix_a)
print("Матриця B:\n", matrix_b)
print("Array\n", array)

Матриця A:
 [[ 8 10  7]
 [ 9  7  7]
 [ 8  8  8]]
Матриця B:
 [[ 7 10  8]
 [ 9  6  9]
 [ 7  9  9]]
Array
 [[195 203 217]
 [175 195 198]
 [184 200 208]]


In [45]:
#Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від
#1 до 5 та перемножте їх між собою.
matrix_a = np.random.randint(1, 6, size=(2, 3))
matrix_b = np.random.randint(1, 6, size=(3, 3))
array = np.dot(matrix_a, matrix_b)
print("Матриця A:\n", matrix_a)
print("Матриця B:\n", matrix_b)
print("Array:\n", array)

Матриця A:
 [[5 1 3]
 [1 1 5]]
Матриця B:
 [[4 1 4]
 [4 3 1]
 [3 5 5]]
Array:
 [[33 23 36]
 [23 29 30]]


In [21]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1
#до 8 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 9, size=(3, 3))
rotate_matrix = np.linalg.inv(matrix) if np.linalg.det(matrix) != 0 else None
print("Матриця:\n", matrix)
if rotate_matrix is not None:
    print("Обернена матриця:\n", rotate_matrix)
else:
    print("Матриця не обернена")

Матриця:
 [[3 8 2]
 [5 1 1]
 [8 8 4]]
Обернена матриця:
 [[ 0.09090909  0.36363636 -0.13636364]
 [ 0.27272727  0.09090909 -0.15909091]
 [-0.72727273 -0.90909091  0.84090909]]


In [46]:
#Створіть матрицю розміром 8x8, заповніть її випадковими дійсними
#числами в діапазоні від 50 до 100 та транспонуйте її.
matrix = np.random.uniform(50, 101, size=(8, 8))
tran_matrix = np.transpose(matrix)
print("Матриця:\n", matrix)
print("Транспонована матриця:\n", tran_matrix)

Матриця:
 [[ 60.69746932  73.66267364  53.33221786  59.60177034  99.23020378
   77.95059906  74.15577385  99.08378302]
 [ 73.68587675  57.52765125  63.17945393  79.06028742  92.33473633
   79.33436695  74.5889414   86.28782979]
 [ 89.54007701  72.85574501  62.64855443  54.22780018 100.92767133
   56.56897431  89.29140078  92.13452732]
 [ 65.04535117  52.92779968  68.08623217  82.70958284  69.12678219
   83.11934534  76.63542619  93.70764796]
 [ 56.94111173  56.99401224  92.90986566  78.64550379  82.77892947
   78.80699229  97.13139713  98.28150398]
 [ 97.95978395 100.69320048  61.92712074  60.34273708  55.09432041
   81.19839549  77.01944404  60.94008018]
 [ 57.7525669   99.56222544  79.36171775  67.32711364  68.54582161
   73.34697204  77.07456963  94.91633325]
 [ 51.84936261  76.80665841  95.01545755  81.02743106  95.40358603
   93.56140687  59.71746657  79.92455124]]
Транспонована матриця:
 [[ 60.69746932  73.68587675  89.54007701  65.04535117  56.94111173
   97.95978395  57.7525669

In [47]:
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними
#числами від -1 до 1, а вектор - випадковими цілими числами в діапазоні від -3 до 3 і знайдіть
#добуток матриці на вектор.
matrix = np.random.uniform(-1, 1, size=(3, 4))
vector = np.random.randint(-3, 4, size=(4, 1))
array = np.dot(matrix, vector)
print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток матриці на вектор:\n", array)

Матриця:
 [[ 0.67944372 -0.04461776  0.22894041  0.33753215]
 [-0.31978915 -0.52160723  0.77103532 -0.06349963]
 [-0.76665144  0.16903025  0.32790921  0.43417025]]
Вектор:
 [[-1]
 [-1]
 [ 3]
 [-2]]
Добуток матриці на вектор:
 [[-0.62306903]
 [ 3.28150159]
 [ 0.71300832]]


In [48]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами
#в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть
#добуток матриці на вектор.
matrix = np.random.randint(1, 11, size=(2, 3))
vector = np.random.rand(3, 1)
array = np.dot(matrix, vector)
print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Array:\n", array)

Матриця:
 [[ 6  3  5]
 [10  5  2]]
Вектор:
 [[0.3923261 ]
 [0.95975599]
 [0.34297932]]
Array:
 [[6.94812117]
 [9.40799961]]


In [49]:
#Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 10 та знайдіть відношення всіх елементів першої матриці до відповідних
#елементів другої матриці (поелементне ділення).
matrix1 = np.random.randint(1, 11, size=(5, 5))
matrix2 = np.random.randint(1, 11, size=(5, 5))
dividing = np.divide(matrix1, matrix2)
print("Матриця A:\n", matrix1)
print("Матриця B:\n", matrix2)
print("Результат ділення:\n", dividing)

Матриця A:
 [[ 5  4  5  7  6]
 [ 5  3 10  3  8]
 [10  1  7 10  8]
 [ 4  2  9  8  4]
 [ 9  6  6 10  9]]
Матриця B:
 [[ 4 10  5  4  2]
 [ 7  6  2  2  8]
 [ 4  2  9  1  1]
 [10  4  4  9  9]
 [ 6  8  5 10  8]]
Результат ділення:
 [[ 1.25        0.4         1.          1.75        3.        ]
 [ 0.71428571  0.5         5.          1.5         1.        ]
 [ 2.5         0.5         0.77777778 10.          8.        ]
 [ 0.4         0.5         2.25        0.88888889  0.44444444]
 [ 1.5         0.75        1.2         1.          1.125     ]]


In [50]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні
#від -10 до 10 та знайдіть різницю їх елементів.
matrix1 = np.random.randint(-10, 11, size=(4, 4))
matrix2 = np.random.randint(-10, 11, size=(4, 4))
equation = np.subtract(matrix1, matrix2)
print("Матриця A:\n", matrix1)
print("Матриця B:\n", matrix2)
print("Різниця:\n", equation)

Матриця A:
 [[ -5   5  -8   4]
 [  1   1   3  -2]
 [ -3   9 -10  -1]
 [ -3  -9   5  -4]]
Матриця B:
 [[  4   6  -2  -1]
 [ -1   1   3  -9]
 [  5  -8   0   0]
 [  6  -1   7 -10]]
Різниця:
 [[ -9  -1  -6   5]
 [  2   0   0   7]
 [ -8  17 -10  -1]
 [ -9  -8  -2   6]]


In [51]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 10 та знайдіть суму елементів матриці, які менше за їх середнє
#арифметичне значення.
matrix = np.random.randint(1, 11, size=(3, 3))
mean = np.mean(matrix)
sum_below_mean = np.sum(matrix[matrix < mean])
print("Матриця:\n", matrix)
print(f"Середнє арифметичне: {mean}")
print(f"Сума елементів менше середнього: {sum_below_mean}")

Матриця:
 [[9 7 5]
 [5 3 5]
 [5 4 1]]
Середнє арифметичне: 4.888888888888889
Сума елементів менше середнього: 8


In [52]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними
#числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить
#середнє гармонічне значення елементів кожного рядка матриці.
matrix = np.random.uniform(-2, 2, size=(3, 3))
harmonic_mean = np.reciprocal(np.mean(np.reciprocal(matrix), axis=1)).reshape(-1, 1)
print("Матриця:\n", matrix)
print("Гармонічне середнє вектор:\n", harmonic_mean)

Матриця:
 [[ 1.04683991  0.58745126  1.12713886]
 [ 0.04165667  1.13496693  0.32030414]
 [-0.12970724 -0.46646068  0.23821424]]
Гармонічне середнє вектор:
 [[ 0.84632754]
 [ 0.10710891]
 [-0.53045036]]


In [53]:
#Висновок
#У ході виконання завдань з використанням бібліотеки NumPy були опрацьовані різноманітні операції з масивами та матрицями,
#що продемонструвало ефективність цієї бібліотеки для наукових обчислень і аналізу даних. Завдання охоплювали
#різні операції та функції, які часто застосовуються в дослідницьких проєктах, аналізі даних та машинному навчанні.